application:
  name: test-app
server:
  port: 7070
  address: 127.0.0.1


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  http:
    converters:
      preferred-json-mapper=gson:
#
#cmz:
#  test: 2